travel/models.py
from . import db
from datetime import datetime
from flask_login import UserMixin

class User(db.Model, UserMixin):
    __tablename__ = 'users' # good practice to specify table name
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), index=True, unique=True, nullable=False)
    emailid = db.Column(db.String(100), index=True, nullable=False)
	#password is never stored in the DB, an encrypted password is stored
	# the storage should be at least 255 chars long
    password_hash = db.Column(db.String(255), nullable=False)
    # relation to call user.comments and comment.name
    comments = db.relationship('Comment', backref='user')

    # string print method
    def __repr__(self):
        return f"Name: {self.name}"

class Destination(db.Model):
    __tablename__ = 'destinations'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80))
    description = db.Column(db.String(200))
    image = db.Column(db.String(400))
    currency = db.Column(db.String(3))
    # ... Create the Comments db.relationship
	# relation to call destination.comments and comment.destination
    comments = db.relationship('Comment', backref='destination')

	# string print method
    def __repr__(self):
        return f"Name: {self.name}"

class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.String(400))
    created_at = db.Column(db.DateTime, default=datetime.now())
    # add the foreign keys
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    destination_id = db.Column(db.Integer, db.ForeignKey('destinations.id'))

    # string print method
    def __repr__(self):
        return f"Comment: {self.text}"

travel/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import TextAreaField, SubmitField, StringField, PasswordField
from wtforms.validators import InputRequired, Email, EqualTo
from flask_wtf.file import FileRequired, FileField, FileAllowed

ALLOWED_FILE = {'PNG', 'JPG', 'JPEG', 'png', 'jpg', 'jpeg'}

#Create new destination
class DestinationForm(FlaskForm):
  name = StringField('Country', validators=[InputRequired()])
  description = TextAreaField('Description', 
            validators=[InputRequired()])
  image = FileField('Destination Image', validators=[
    FileRequired(message='Image cannot be empty'),
    FileAllowed(ALLOWED_FILE, message='Only supports PNG, JPG, png, jpg')])
  currency = StringField('Currency', validators=[InputRequired()])
  submit = SubmitField("Create")
    
#User login
class LoginForm(FlaskForm):
    user_name = StringField("User Name", validators=[InputRequired('Enter user name')])
    password = PasswordField("Password", validators=[InputRequired('Enter user password')])
    submit = SubmitField("Login")

#User register
class RegisterForm(FlaskForm):
    user_name = StringField("User Name", validators=[InputRequired()])
    email_id = StringField("Email Address", validators=[Email("Please enter a valid email")])
    
    #linking two fields - password should be equal to data entered in confirm
    password = PasswordField("Password", validators=[InputRequired(),
                  EqualTo('confirm', message="Passwords should match")])
    confirm = PasswordField("Confirm Password")
    #submit button
    submit = SubmitField("Register")

#User comment
class CommentForm(FlaskForm):
  text = TextAreaField('Comment', [InputRequired()])
  submit = SubmitField('Create')

travel/__init__.py
from flask import Flask, render_template
from flask_bootstrap import Bootstrap5
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bcrypt import Bcrypt
import datetime

db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    #we use this utility module to display forms quickly
    Bootstrap5(app)

    #this is a much safer way to store passwords
    Bcrypt(app)

    #a secret key for the session object
    #(it would be better to use an environment variable here)
    app.secret_key = 'somerandomvalue'

    #Configue and initialise DB
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///traveldb.sqlite'
    db.init_app(app)

    #config upload folder
    UPLOAD_FOLDER = '/static/image'
    app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER 
    
    # initialise the login manager
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    # create a user loader function takes userid and returns User
    from .models import User  # importing here to avoid circular references
    @login_manager.user_loader
    def load_user(user_id):
        return db.session.scalar(db.select(User).where(User.id==user_id))

    # add Blueprints
    from . import views
    app.register_blueprint(views.mainbp)
    from . import destinations
    app.register_blueprint(destinations.destbp)
    from . import auth
    app.register_blueprint(auth.authbp)

    @app.errorhandler(404) 
    # inbuilt function which takes error as parameter 
    def not_found(e): 
      return render_template("404.html", error=e)

    # this creates a dictionary of variables that are available
    # to all html templates
    @app.context_processor
    def get_context():
      year = datetime.datetime.today().year
      return dict(year=year)

    return app

travel/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash
from .forms import LoginForm, RegisterForm
#new imports:
from flask_login import login_user, login_required, logout_user
from flask_bcrypt import generate_password_hash, check_password_hash
from .models import User
from . import db

#create a blueprint
authbp = Blueprint('auth', __name__ )

@authbp.route('/register', methods=['GET', 'POST'])
def register():
    register = RegisterForm()
    #the validation of form is fine, HTTP request is POST
    if (register.validate_on_submit()==True):
            #get username, password and email from the form
            uname = register.user_name.data
            pwd = register.password.data
            email = register.email_id.data
            #check if a user exists
            user = db.session.scalar(db.select(User).where(User.name==uname))
            if user:#this returns true when user is not None
                flash('Username already exists, please try another')
                return redirect(url_for('auth.register'))
            # don't store the password in plaintext!
            pwd_hash = generate_password_hash(pwd)
            #create a new User model object
            new_user = User(name=uname, password_hash=pwd_hash, emailid=email)
            db.session.add(new_user)
            db.session.commit()
            #commit to the database and redirect to HTML page
            return redirect(url_for('main.index'))
    #the else is called when the HTTP request calling this page is a GET
    else:
        return render_template('user.html', form=register, heading='Register')

@authbp.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm()
    error = None
    if(login_form.validate_on_submit()==True):
        #get the username and password from the database
        user_name = login_form.user_name.data
        password = login_form.password.data
        user = db.session.scalar(db.select(User).where(User.name==user_name))
        #if there is no user with that name
        if user is None:
            error = 'Incorrect username'#could be a security risk to give this much info away
        #check the password - notice password hash function
        elif not check_password_hash(user.password_hash, password): # takes the hash and password
            error = 'Incorrect password'
        if error is None:
            #all good, set the login_user of flask_login to manage the user
            login_user(user)
            return redirect(url_for('main.index'))
        else:
            flash(error)
    return render_template('user.html', form=login_form, heading='Login')

@authbp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

travel/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from .models import Destination
from . import db

mainbp = Blueprint('main', __name__)

@mainbp.route('/')
def index():
    destinations = db.session.scalars(db.select(Destination)).all()    
    return render_template('index.html', destinations=destinations)

@mainbp.route('/search')
def search():
    if request.args['search'] and request.args['search'] != "":
        print(request.args['search'])
        query = "%" + request.args['search'] + "%"
        destinations = db.session.scalars(db.select(Destination).where(Destination.description.like(query)))
        return render_template('index.html', destinations=destinations)
    else:
        return redirect(url_for('main.index'))

travel/templates/base.html
<html>

<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>My Travel App</title>
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>
   <!-- Header -->
   <header class="bg-light border-bottom">

      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
         <div class="container">

            <!-- Your Travel App Name or Logo -->
            <a href="/" class="navbar-brand">My Travel App</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
               data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
               aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Navbar -->
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
               <div class="navbar-nav ml-auto">

                  <!-- Register/Login/Logout and welcome -->
                  {% if current_user.is_authenticated %}
                     <a class="nav-item nav-link disabled text-muted" href="#">Welcome {{current_user.name}}</a>
                     <a class="nav-item nav-link" href="{{ url_for('auth.logout') }}">Log Out</a>
                  {% else %}
                     <a class="nav-item nav-link" href="{{ url_for('auth.register') }}">Register</a>
                     <a class="nav-item nav-link" href="{{ url_for('auth.login') }}">Log In</a>
                  {% endif %}

                  <a class="nav-item nav-link" href="{{ url_for('destination.create') }}">Destinations</a>
                  <a class="nav-item nav-link" href="#">Bookings</a>
                  
               </div>
            </div>
         </div>
      </nav>
      <!-- flashes any messages to the user -->
      {% with messages = get_flashed_messages() %}
      {% if messages %} <!-- check if there are any messages -->
      <div class="container-fluid">
         <div class="row mt-3 mb-3">
            <div class="col-md-12">
            {% for message in messages %} <!--loop through the messages-->
            <div class="alert alert-info">{{ message }}</div> <!--display as alert-->
            {% endfor %}
         </div>
      </div>
      </div>
      {% endif %}
      {% endwith %}
    
      {% block header %}

      {% endblock %}

   </header>
      
   {% block content %}

   {% endblock %}
   
    <footer class="footer">
        <div class="text-center py-2 bg-light">
            <span class="text-dark">Copyright &copy; {{ year }}</span>
        </div>
    </footer> 
   </body>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</html>

travel/templates/destinations/create.html
{% extends 'base.html' %}

{% from 'bootstrap5/form.html' import render_form %}

{% block content %}

  <div class="container">
    <div class="row mt-5">
      <div class="col-md-12">
        <h1>Add Travel Destination</h1>
        <p>Enter a country that you will help clients travel to.</p>
        {{ render_form(form) }}
      </div>
    </div>
  </div>

{% endblock %}

travel/templates/destinations/show.html
{% extends 'base.html' %}

{% from 'bootstrap5/form.html' import render_form %}

{% block content %}

<div class="container">  
    <div class="row mt-5 mb-3">  
      <div class="col-md-12">  
        <div class="float-left">  
          <h1 class="mb-0">{{ destination.name }}</h1>  
          <p>Popular Destination</p>  
        </div>  
 
        <div class="float-right text-right">  
          <p class="mb-0">1 AUD equals</p>  
          <h2 id="exchange-rate">0.62 {{ destination.currency }}</h1>  
        </div>  
      </div>  
    </div>  
 
    <!-- Destination --> 
    <div class="row">  
      <div class="col-md-12">  
        <div class="card my-3">  
          <div class="card-body">  
            <div class="media">  
              <img class="align-self-start mr-3" src="{{ destination.image }}">  
              <div class="media-body">  
                <small class="font-weight-bold text-muted">Stay 2 nights</small>  
                <h5 class="mt-0">{{ destination.name }}</h5>  
                <p>{{ destination.description }}</p>  
                <a href="#" class="btn btn-danger">Book Now</a>  
              </div>  
            </div>  
          </div>  
        </div>  
      </div>  
    </div>
    <hr>
    <!-- Comments -->  
    <div class="row">  
      <div class="col-md-12">  
        <h2>Comments</h1>  
      </div>  
    </div>  
 
    <div class="row border-bottom"> 
      {{ render_form(form,"/destinations/{0}/comment".format(destination.id)) }}
      
      {% for comment in destination.comments %}
      <div class="col-md-12">  
        <b>{{ comment.user.name }} <span class="ml-2 text-muted">January 2024</span></b>
        <p>{{ comment.text }}</p>  
      </div> 
      {% endfor %} 
    </div>  
  </div> 

{% endblock %}

travel/templates/index.html
{% extends 'base.html' %}

{% block header %}
      <!--Jumbotron-->
      <div class="container">
         <div class="row justify-content-center mt-5 pb-4">
            <div class="col-md-8">
               <div class="card shadow p-5 mb-5 bg-light">
                  <h1 class="text-center mb-3">Find our best travel deals</h1>

                  <form class="form-inline d-flex flex-nowrap" action="{{url_for('main.search')}}" >
                     <input type="text" name="search" class="form-control flex-grow-1 my-1 mr-sm-2" id="SearchForm">
                     <button type="submit" class="flex-shrink-1 btn btn-primary my-1">Submit</button>
                   </form>
                  
               </div>
            </div>
         </div>
      </div>
{% endblock %}

{% block content %}   
      <div class="container">
         <div class="row mt-5 mb-5 justify-content-center">
            <div class="col-md-10">
               <div class="media border p-3 d-flex justify-content-start">
                  <img class="align-self-center me-3" style="max-width:120px"
                     src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Earth_Western_Hemisphere_transparent_background.png/600px-Earth_Western_Hemisphere_transparent_background.png"
                     alt="Planet Earth">
                  <div class="align-self-center media-body">
                     <h5 class="mt-0">Find the best destinations on earth</h5>
                     <p class="d-none d-sm-block">Cras sit amet nibh libero, in gravida nulla. Nulla vel metus
                        scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra
                        turpis. Fusce condimentum nunc ac nisi vulputate fringilla.</p>
                     <a href="#" class="btn btn-primary">Join Now</a>
                  </div>
               </div>
            </div>
         </div>

         <div class="card-group">
            {% for destination in destinations %}
            <div class="card mx-3">
               <img class="card-img-top"
                  src="{{ destination.image }}" alt="destination picture">
               <div class="card-body">
                  <h5 class="card-title">{{ destination.name }}</h5>
                  <p class="card-text">{{ destination.description }}</p>
               </div>
               <div class="card-footer"><a href="{{ url_for('destination.show', id=destination.id) }}" class ="btn btn-danger"> View Details </a></div>
            </div>
            {% endfor %}
         </div>
      </div>
{% endblock %}

travel/templates/user.html
{% extends "base.html" %}

{% from 'bootstrap5/form.html' import render_form %}

{% block content %}

<div class="container">
<div class="page-header">
    <h4>{{heading}}</h4>
</div>

<!-- Form rendering is simple and easy if using bootstrap -->
<div class="col-md-6 ml-5">
  {{render_form(form)}}
</div>

{% endblock %}